version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
     POSTGRES_DB: warthog-starter-development
     POSTGRES_PASSWORD:
     POSTGRES_USER: sean

volumes:
  db_data: